USE [master]
GO
/****** Object:  Database [actividad10]    Script Date: 28/10/2024 11:14:46 ******/
CREATE DATABASE [actividad10]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'actividad10', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\actividad10.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'actividad10_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\actividad10_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [actividad10] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [actividad10].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [actividad10] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [actividad10] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [actividad10] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [actividad10] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [actividad10] SET ARITHABORT OFF 
GO
ALTER DATABASE [actividad10] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [actividad10] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [actividad10] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [actividad10] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [actividad10] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [actividad10] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [actividad10] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [actividad10] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [actividad10] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [actividad10] SET  ENABLE_BROKER 
GO
ALTER DATABASE [actividad10] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [actividad10] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [actividad10] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [actividad10] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [actividad10] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [actividad10] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [actividad10] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [actividad10] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [actividad10] SET  MULTI_USER 
GO
ALTER DATABASE [actividad10] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [actividad10] SET DB_CHAINING OFF 
GO
ALTER DATABASE [actividad10] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [actividad10] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [actividad10] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [actividad10] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [actividad10] SET QUERY_STORE = OFF
GO
USE [actividad10]
GO
/****** Object:  Table [dbo].[Empleado]    Script Date: 28/10/2024 11:14:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Empleado](
	[APELLIDONOMBRE] [varchar](50) NULL,
	[DNI] [int] NULL,
	[SUELDOBRUTO] [float] NULL
) ON [PRIMARY]
GO
INSERT [dbo].[Empleado] ([APELLIDONOMBRE], [DNI], [SUELDOBRUTO]) VALUES (N'REY, CARLOS', 12345678, 123456)
GO
INSERT [dbo].[Empleado] ([APELLIDONOMBRE], [DNI], [SUELDOBRUTO]) VALUES (N'Rey, Yanina', 22334455, 123456)
GO
INSERT [dbo].[Empleado] ([APELLIDONOMBRE], [DNI], [SUELDOBRUTO]) VALUES (N'Rey, Maia', 56231231, 2255441)
GO
INSERT [dbo].[Empleado] ([APELLIDONOMBRE], [DNI], [SUELDOBRUTO]) VALUES (N'Rey, Franco', 45678912, 123456)
GO
INSERT [dbo].[Empleado] ([APELLIDONOMBRE], [DNI], [SUELDOBRUTO]) VALUES (N'asd, asd', 12345678, 123665)
GO
USE [master]
GO
ALTER DATABASE [actividad10] SET  READ_WRITE 
GO
